### ISSUE TITLE
Wheels for python 3.10 and newer

### ISSUE THREAD

**Issue by ikatechis** [patmjen/pygorpho#3]
Hi @patmjen

Thank you for this amazing little library!

Is it possible to create wheels for python 3.10 (and other newer versions) on pypi server?

**Comment by patmjen** [comment]
Wheels for all Python 3 versions should now be available under version 1.0.1.
It is the same as version 1.0.0 - I only removed the requirements for certain Python versions.

Since the code does not use any advanced/new Python 3 features, allowing all Python 3 versions should not be a problem. I just tested with Python 3.11 and that seems to work with no issues.

I apologize for the long wait. Updating the build systems for newer versions of Visual Studio proved to be very difficult so I had to resort to manually fixing the wheel files...

**Comment by ikatechis** [comment]
@patmjen Thank you so much! Again congrats on the nice work :muscle:
